stages:
 - deploy-to-prod
 - deploy-to-stag
to-prod:
 stage: deploy-to-prod
 rules:
  - if: '$CI_COMMIT_BRANCH == "develop"'
 script: 
  - pwd
  - ls -la
  - cd ../
  - pwd
  - sudo rm -rf /var/www/html/chicstays-backend
  - ls -la /var/www/html
  - sudo cp -r chicstays-backend/ /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - cd /var/www/html/chicstays-backend
  - pwd
  - composer install
  - cp ~/.env .env
  - ls -la /var/www/html/chicstays-backend
 tags:
  - prod
 artifacts:
   paths:
     - results.log
   expire_in: 2 week

to-stag:
 stage: deploy-to-stag
 rules:
  - if: '$CI_COMMIT_BRANCH == "milestone5" || '$CI_COMMIT_BRANCH == "milestone6" || '$CI_COMMIT_BRANCH == "milestone7" || '$CI_COMMIT_BRANCH == "milestone8"'
 script: 
  - pwd
  - ls -la
  - cd ../
  - pwd
  - sudo rm -rf /var/www/html/chicstays-backend
  - ls -la /var/www/html
  - sudo cp -r chicstays-backend/ /var/www/html/chicstays-backend
  - ls -la /var/www/html/chicstays-backend
  - cd /var/www/html/chicstays-backend
  - pwd
  - composer install
  - cp ~/.env .env
  - ls -la /var/www/html/chicstays-backend
 tags:
  - stag
 artifacts:
   paths:
     - results.log
   expire_in: 2 week  
