stages:
 - deploy-to-prod
 - deploy-to-stag
to-prod:
 stage: deploy-to-prod
 rules:
  - if: '$CI_COMMIT_BRANCH == "develop"'
 script: 
  - pwd
  - ls -la
  - npm install
  - npm run prod
  - sudo rm -rf ~/chicstays-frontend/dist/*
  - sudo cp -r dist/* ~/chicstays-frontend/dist
 tags:
  - prod
 artifacts:
   paths:
     - results.log
   expire_in: 2 week  
   
to-stag:
 stage: deploy-to-stag
 rules:
  - if: '$CI_COMMIT_BRANCH == "milestone5" || $CI_COMMIT_BRANCH == "milestone6" || $CI_COMMIT_BRANCH == "milestone7" || $CI_COMMIT_BRANCH == "milestone8"'
 script: 
  - pwd
  - ls -la
  - npm install
  - npm run prod
  - sudo rm -rf ~/chicstays-frontend/dist/*
  - sudo cp -r dist/* ~/chicstays-frontend/dist
 tags:
  - stag
 artifacts:
   paths:
     - results.log
   expire_in: 2 week  
